//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MosaicSample.UI.FinishingStationModule.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FinishingStationModuleServiceFault", Namespace="http://schemas.datacontract.org/2004/07/MosaicSample.FinishingStationModule")]
    [System.SerializableAttribute()]
    public partial class FinishingStationModuleServiceFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IFinishingStationModuleService", CallbackContract=typeof(MosaicSample.UI.FinishingStationModule.ServiceReference.IFinishingStationModuleServiceCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IFinishingStationModuleService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinishingStationModuleServiceREST/KeepAlive", ReplyAction="http://tempuri.org/IFinishingStationModuleServiceREST/KeepAliveResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MosaicSample.UI.FinishingStationModule.ServiceReference.FinishingStationModuleServiceFault), Action="http://tempuri.org/IFinishingStationModuleServiceREST/KeepAliveFinishingStationMo" +
            "duleServiceFaultFault", Name="FinishingStationModuleServiceFault", Namespace="http://schemas.datacontract.org/2004/07/MosaicSample.FinishingStationModule")]
        bool KeepAlive();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinishingStationModuleServiceREST/KeepAlive", ReplyAction="http://tempuri.org/IFinishingStationModuleServiceREST/KeepAliveResponse")]
        System.Threading.Tasks.Task<bool> KeepAliveAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinishingStationModuleServiceREST/get_IsInitialized", ReplyAction="http://tempuri.org/IFinishingStationModuleServiceREST/get_IsInitializedResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MosaicSample.UI.FinishingStationModule.ServiceReference.FinishingStationModuleServiceFault), Action="http://tempuri.org/IFinishingStationModuleServiceREST/get_IsInitializedFinishingS" +
            "tationModuleServiceFaultFault", Name="FinishingStationModuleServiceFault", Namespace="http://schemas.datacontract.org/2004/07/MosaicSample.FinishingStationModule")]
        bool get_IsInitialized();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinishingStationModuleServiceREST/get_IsInitialized", ReplyAction="http://tempuri.org/IFinishingStationModuleServiceREST/get_IsInitializedResponse")]
        System.Threading.Tasks.Task<bool> get_IsInitializedAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinishingStationModuleServiceREST/Start", ReplyAction="http://tempuri.org/IFinishingStationModuleServiceREST/StartResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MosaicSample.UI.FinishingStationModule.ServiceReference.FinishingStationModuleServiceFault), Action="http://tempuri.org/IFinishingStationModuleServiceREST/StartFinishingStationModule" +
            "ServiceFaultFault", Name="FinishingStationModuleServiceFault", Namespace="http://schemas.datacontract.org/2004/07/MosaicSample.FinishingStationModule")]
        void Start();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinishingStationModuleServiceREST/Start", ReplyAction="http://tempuri.org/IFinishingStationModuleServiceREST/StartResponse")]
        System.Threading.Tasks.Task StartAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinishingStationModuleServiceREST/Stop", ReplyAction="http://tempuri.org/IFinishingStationModuleServiceREST/StopResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MosaicSample.UI.FinishingStationModule.ServiceReference.FinishingStationModuleServiceFault), Action="http://tempuri.org/IFinishingStationModuleServiceREST/StopFinishingStationModuleS" +
            "erviceFaultFault", Name="FinishingStationModuleServiceFault", Namespace="http://schemas.datacontract.org/2004/07/MosaicSample.FinishingStationModule")]
        void Stop();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinishingStationModuleServiceREST/Stop", ReplyAction="http://tempuri.org/IFinishingStationModuleServiceREST/StopResponse")]
        System.Threading.Tasks.Task StopAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinishingStationModuleServiceREST/ResetAlarms", ReplyAction="http://tempuri.org/IFinishingStationModuleServiceREST/ResetAlarmsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MosaicSample.UI.FinishingStationModule.ServiceReference.FinishingStationModuleServiceFault), Action="http://tempuri.org/IFinishingStationModuleServiceREST/ResetAlarmsFinishingStation" +
            "ModuleServiceFaultFault", Name="FinishingStationModuleServiceFault", Namespace="http://schemas.datacontract.org/2004/07/MosaicSample.FinishingStationModule")]
        void ResetAlarms(int moduleInstance);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinishingStationModuleServiceREST/ResetAlarms", ReplyAction="http://tempuri.org/IFinishingStationModuleServiceREST/ResetAlarmsResponse")]
        System.Threading.Tasks.Task ResetAlarmsAsync(int moduleInstance);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinishingStationModuleServiceREST/SubscribeEvents", ReplyAction="http://tempuri.org/IFinishingStationModuleServiceREST/SubscribeEventsResponse")]
        void SubscribeEvents(int moduleInstance);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinishingStationModuleServiceREST/SubscribeEvents", ReplyAction="http://tempuri.org/IFinishingStationModuleServiceREST/SubscribeEventsResponse")]
        System.Threading.Tasks.Task SubscribeEventsAsync(int moduleInstance);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinishingStationModuleServiceREST/UnsubscribeEvents", ReplyAction="http://tempuri.org/IFinishingStationModuleServiceREST/UnsubscribeEventsResponse")]
        void UnsubscribeEvents(int moduleInstance);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinishingStationModuleServiceREST/UnsubscribeEvents", ReplyAction="http://tempuri.org/IFinishingStationModuleServiceREST/UnsubscribeEventsResponse")]
        System.Threading.Tasks.Task UnsubscribeEventsAsync(int moduleInstance);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinishingStationModuleServiceREST/UpdateZebraPrinterIp", ReplyAction="http://tempuri.org/IFinishingStationModuleServiceREST/UpdateZebraPrinterIpRespons" +
            "e")]
        void UpdateZebraPrinterIp(int moduleInstance, string ipaddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinishingStationModuleServiceREST/UpdateZebraPrinterIp", ReplyAction="http://tempuri.org/IFinishingStationModuleServiceREST/UpdateZebraPrinterIpRespons" +
            "e")]
        System.Threading.Tasks.Task UpdateZebraPrinterIpAsync(int moduleInstance, string ipaddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinishingStationModuleServiceREST/UpdateZplTemplateUrl", ReplyAction="http://tempuri.org/IFinishingStationModuleServiceREST/UpdateZplTemplateUrlRespons" +
            "e")]
        void UpdateZplTemplateUrl(int moduleInstance, string url);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinishingStationModuleServiceREST/UpdateZplTemplateUrl", ReplyAction="http://tempuri.org/IFinishingStationModuleServiceREST/UpdateZplTemplateUrlRespons" +
            "e")]
        System.Threading.Tasks.Task UpdateZplTemplateUrlAsync(int moduleInstance, string url);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFinishingStationModuleServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPlatformModuleWcfService/ModuleStateChanged")]
        void ModuleStateChanged(VP.FF.PT.Common.PlatformEssentials.Entities.DTOs.PlatformModuleDTO module);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPlatformModuleWcfService/MetricsChanged")]
        void MetricsChanged(VP.FF.PT.Common.PlatformEssentials.Entities.DTOs.MetricsDTO metrics);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPlatformModuleWcfService/SendUserNotification")]
        void SendUserNotification(VP.FF.PT.Common.PlatformEssentials.MessageType type, string message, System.TimeSpan duration);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IFinishingStationModuleService/ZebraPrinterIpChanged")]
        void ZebraPrinterIpChanged(string ipAddress);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IFinishingStationModuleService/ZplTemplateChanged")]
        void ZplTemplateChanged(string url);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFinishingStationModuleServiceChannel : MosaicSample.UI.FinishingStationModule.ServiceReference.IFinishingStationModuleService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FinishingStationModuleServiceClient : System.ServiceModel.DuplexClientBase<MosaicSample.UI.FinishingStationModule.ServiceReference.IFinishingStationModuleService>, MosaicSample.UI.FinishingStationModule.ServiceReference.IFinishingStationModuleService {
        
        public FinishingStationModuleServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public FinishingStationModuleServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public FinishingStationModuleServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public FinishingStationModuleServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public FinishingStationModuleServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public bool KeepAlive() {
            return base.Channel.KeepAlive();
        }
        
        public System.Threading.Tasks.Task<bool> KeepAliveAsync() {
            return base.Channel.KeepAliveAsync();
        }
        
        public bool get_IsInitialized() {
            return base.Channel.get_IsInitialized();
        }
        
        public System.Threading.Tasks.Task<bool> get_IsInitializedAsync() {
            return base.Channel.get_IsInitializedAsync();
        }
        
        public void Start() {
            base.Channel.Start();
        }
        
        public System.Threading.Tasks.Task StartAsync() {
            return base.Channel.StartAsync();
        }
        
        public void Stop() {
            base.Channel.Stop();
        }
        
        public System.Threading.Tasks.Task StopAsync() {
            return base.Channel.StopAsync();
        }
        
        public void ResetAlarms(int moduleInstance) {
            base.Channel.ResetAlarms(moduleInstance);
        }
        
        public System.Threading.Tasks.Task ResetAlarmsAsync(int moduleInstance) {
            return base.Channel.ResetAlarmsAsync(moduleInstance);
        }
        
        public void SubscribeEvents(int moduleInstance) {
            base.Channel.SubscribeEvents(moduleInstance);
        }
        
        public System.Threading.Tasks.Task SubscribeEventsAsync(int moduleInstance) {
            return base.Channel.SubscribeEventsAsync(moduleInstance);
        }
        
        public void UnsubscribeEvents(int moduleInstance) {
            base.Channel.UnsubscribeEvents(moduleInstance);
        }
        
        public System.Threading.Tasks.Task UnsubscribeEventsAsync(int moduleInstance) {
            return base.Channel.UnsubscribeEventsAsync(moduleInstance);
        }
        
        public void UpdateZebraPrinterIp(int moduleInstance, string ipaddress) {
            base.Channel.UpdateZebraPrinterIp(moduleInstance, ipaddress);
        }
        
        public System.Threading.Tasks.Task UpdateZebraPrinterIpAsync(int moduleInstance, string ipaddress) {
            return base.Channel.UpdateZebraPrinterIpAsync(moduleInstance, ipaddress);
        }
        
        public void UpdateZplTemplateUrl(int moduleInstance, string url) {
            base.Channel.UpdateZplTemplateUrl(moduleInstance, url);
        }
        
        public System.Threading.Tasks.Task UpdateZplTemplateUrlAsync(int moduleInstance, string url) {
            return base.Channel.UpdateZplTemplateUrlAsync(moduleInstance, url);
        }
    }
}
