//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MosaicSample.UI.DemoModuleC.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IDemoModuleCServiceFault", Namespace="http://schemas.datacontract.org/2004/07/MosaicSample.DemoModuleC")]
    [System.SerializableAttribute()]
    public partial class IDemoModuleCServiceFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IDemoModuleCService", CallbackContract=typeof(MosaicSample.UI.DemoModuleC.ServiceReference.IDemoModuleCServiceCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IDemoModuleCService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemoModuleCServiceREST/KeepAlive", ReplyAction="http://tempuri.org/IDemoModuleCServiceREST/KeepAliveResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MosaicSample.UI.DemoModuleC.ServiceReference.IDemoModuleCServiceFault), Action="http://tempuri.org/IDemoModuleCServiceREST/KeepAliveIDemoModuleCServiceFaultFault" +
            "", Name="IDemoModuleCServiceFault", Namespace="http://schemas.datacontract.org/2004/07/MosaicSample.DemoModuleC")]
        bool KeepAlive();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemoModuleCServiceREST/KeepAlive", ReplyAction="http://tempuri.org/IDemoModuleCServiceREST/KeepAliveResponse")]
        System.Threading.Tasks.Task<bool> KeepAliveAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemoModuleCServiceREST/get_IsInitialized", ReplyAction="http://tempuri.org/IDemoModuleCServiceREST/get_IsInitializedResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MosaicSample.UI.DemoModuleC.ServiceReference.IDemoModuleCServiceFault), Action="http://tempuri.org/IDemoModuleCServiceREST/get_IsInitializedIDemoModuleCServiceFa" +
            "ultFault", Name="IDemoModuleCServiceFault", Namespace="http://schemas.datacontract.org/2004/07/MosaicSample.DemoModuleC")]
        bool get_IsInitialized();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemoModuleCServiceREST/get_IsInitialized", ReplyAction="http://tempuri.org/IDemoModuleCServiceREST/get_IsInitializedResponse")]
        System.Threading.Tasks.Task<bool> get_IsInitializedAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemoModuleCServiceREST/Start", ReplyAction="http://tempuri.org/IDemoModuleCServiceREST/StartResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MosaicSample.UI.DemoModuleC.ServiceReference.IDemoModuleCServiceFault), Action="http://tempuri.org/IDemoModuleCServiceREST/StartIDemoModuleCServiceFaultFault", Name="IDemoModuleCServiceFault", Namespace="http://schemas.datacontract.org/2004/07/MosaicSample.DemoModuleC")]
        void Start(int moduleInstance);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemoModuleCServiceREST/Start", ReplyAction="http://tempuri.org/IDemoModuleCServiceREST/StartResponse")]
        System.Threading.Tasks.Task StartAsync(int moduleInstance);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemoModuleCServiceREST/Stop", ReplyAction="http://tempuri.org/IDemoModuleCServiceREST/StopResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MosaicSample.UI.DemoModuleC.ServiceReference.IDemoModuleCServiceFault), Action="http://tempuri.org/IDemoModuleCServiceREST/StopIDemoModuleCServiceFaultFault", Name="IDemoModuleCServiceFault", Namespace="http://schemas.datacontract.org/2004/07/MosaicSample.DemoModuleC")]
        void Stop(int moduleInstance);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemoModuleCServiceREST/Stop", ReplyAction="http://tempuri.org/IDemoModuleCServiceREST/StopResponse")]
        System.Threading.Tasks.Task StopAsync(int moduleInstance);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemoModuleCServiceREST/ResetAlarms", ReplyAction="http://tempuri.org/IDemoModuleCServiceREST/ResetAlarmsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MosaicSample.UI.DemoModuleC.ServiceReference.IDemoModuleCServiceFault), Action="http://tempuri.org/IDemoModuleCServiceREST/ResetAlarmsIDemoModuleCServiceFaultFau" +
            "lt", Name="IDemoModuleCServiceFault", Namespace="http://schemas.datacontract.org/2004/07/MosaicSample.DemoModuleC")]
        void ResetAlarms(int moduleInstance);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemoModuleCServiceREST/ResetAlarms", ReplyAction="http://tempuri.org/IDemoModuleCServiceREST/ResetAlarmsResponse")]
        System.Threading.Tasks.Task ResetAlarmsAsync(int moduleInstance);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemoModuleCServiceREST/SubscribeEvents", ReplyAction="http://tempuri.org/IDemoModuleCServiceREST/SubscribeEventsResponse")]
        void SubscribeEvents(int moduleInstance);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemoModuleCServiceREST/SubscribeEvents", ReplyAction="http://tempuri.org/IDemoModuleCServiceREST/SubscribeEventsResponse")]
        System.Threading.Tasks.Task SubscribeEventsAsync(int moduleInstance);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemoModuleCServiceREST/UnsubscribeEvents", ReplyAction="http://tempuri.org/IDemoModuleCServiceREST/UnsubscribeEventsResponse")]
        void UnsubscribeEvents(int moduleInstance);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemoModuleCServiceREST/UnsubscribeEvents", ReplyAction="http://tempuri.org/IDemoModuleCServiceREST/UnsubscribeEventsResponse")]
        System.Threading.Tasks.Task UnsubscribeEventsAsync(int moduleInstance);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDemoModuleCServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPlatformModuleWcfService/ModuleStateChanged")]
        void ModuleStateChanged(VP.FF.PT.Common.PlatformEssentials.Entities.DTOs.PlatformModuleDTO module);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPlatformModuleWcfService/MetricsChanged")]
        void MetricsChanged(VP.FF.PT.Common.PlatformEssentials.Entities.DTOs.MetricsDTO metrics);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPlatformModuleWcfService/SendUserNotification")]
        void SendUserNotification(VP.FF.PT.Common.PlatformEssentials.MessageType type, string message, System.TimeSpan duration);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDemoModuleCServiceChannel : MosaicSample.UI.DemoModuleC.ServiceReference.IDemoModuleCService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DemoModuleCServiceClient : System.ServiceModel.DuplexClientBase<MosaicSample.UI.DemoModuleC.ServiceReference.IDemoModuleCService>, MosaicSample.UI.DemoModuleC.ServiceReference.IDemoModuleCService {
        
        public DemoModuleCServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public DemoModuleCServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public DemoModuleCServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public DemoModuleCServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public DemoModuleCServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public bool KeepAlive() {
            return base.Channel.KeepAlive();
        }
        
        public System.Threading.Tasks.Task<bool> KeepAliveAsync() {
            return base.Channel.KeepAliveAsync();
        }
        
        public bool get_IsInitialized() {
            return base.Channel.get_IsInitialized();
        }
        
        public System.Threading.Tasks.Task<bool> get_IsInitializedAsync() {
            return base.Channel.get_IsInitializedAsync();
        }
        
        public void Start(int moduleInstance) {
            base.Channel.Start(moduleInstance);
        }
        
        public System.Threading.Tasks.Task StartAsync(int moduleInstance) {
            return base.Channel.StartAsync(moduleInstance);
        }
        
        public void Stop(int moduleInstance) {
            base.Channel.Stop(moduleInstance);
        }
        
        public System.Threading.Tasks.Task StopAsync(int moduleInstance) {
            return base.Channel.StopAsync(moduleInstance);
        }
        
        public void ResetAlarms(int moduleInstance) {
            base.Channel.ResetAlarms(moduleInstance);
        }
        
        public System.Threading.Tasks.Task ResetAlarmsAsync(int moduleInstance) {
            return base.Channel.ResetAlarmsAsync(moduleInstance);
        }
        
        public void SubscribeEvents(int moduleInstance) {
            base.Channel.SubscribeEvents(moduleInstance);
        }
        
        public System.Threading.Tasks.Task SubscribeEventsAsync(int moduleInstance) {
            return base.Channel.SubscribeEventsAsync(moduleInstance);
        }
        
        public void UnsubscribeEvents(int moduleInstance) {
            base.Channel.UnsubscribeEvents(moduleInstance);
        }
        
        public System.Threading.Tasks.Task UnsubscribeEventsAsync(int moduleInstance) {
            return base.Channel.UnsubscribeEventsAsync(moduleInstance);
        }
    }
}
