//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MosaicSample.UI.DemoModuleA.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IDemoModuleAServiceFault", Namespace="http://schemas.datacontract.org/2004/07/MosaicSample.DemoModuleA")]
    [System.SerializableAttribute()]
    public partial class IDemoModuleAServiceFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IDemoModuleAService", CallbackContract=typeof(MosaicSample.UI.DemoModuleA.ServiceReference.IDemoModuleAServiceCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IDemoModuleAService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemoModuleAServiceREST/KeepAlive", ReplyAction="http://tempuri.org/IDemoModuleAServiceREST/KeepAliveResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MosaicSample.UI.DemoModuleA.ServiceReference.IDemoModuleAServiceFault), Action="http://tempuri.org/IDemoModuleAServiceREST/KeepAliveIDemoModuleAServiceFaultFault" +
            "", Name="IDemoModuleAServiceFault", Namespace="http://schemas.datacontract.org/2004/07/MosaicSample.DemoModuleA")]
        bool KeepAlive();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemoModuleAServiceREST/KeepAlive", ReplyAction="http://tempuri.org/IDemoModuleAServiceREST/KeepAliveResponse")]
        System.Threading.Tasks.Task<bool> KeepAliveAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemoModuleAServiceREST/get_IsInitialized", ReplyAction="http://tempuri.org/IDemoModuleAServiceREST/get_IsInitializedResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MosaicSample.UI.DemoModuleA.ServiceReference.IDemoModuleAServiceFault), Action="http://tempuri.org/IDemoModuleAServiceREST/get_IsInitializedIDemoModuleAServiceFa" +
            "ultFault", Name="IDemoModuleAServiceFault", Namespace="http://schemas.datacontract.org/2004/07/MosaicSample.DemoModuleA")]
        bool get_IsInitialized();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemoModuleAServiceREST/get_IsInitialized", ReplyAction="http://tempuri.org/IDemoModuleAServiceREST/get_IsInitializedResponse")]
        System.Threading.Tasks.Task<bool> get_IsInitializedAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemoModuleAServiceREST/Start", ReplyAction="http://tempuri.org/IDemoModuleAServiceREST/StartResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MosaicSample.UI.DemoModuleA.ServiceReference.IDemoModuleAServiceFault), Action="http://tempuri.org/IDemoModuleAServiceREST/StartIDemoModuleAServiceFaultFault", Name="IDemoModuleAServiceFault", Namespace="http://schemas.datacontract.org/2004/07/MosaicSample.DemoModuleA")]
        void Start();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemoModuleAServiceREST/Start", ReplyAction="http://tempuri.org/IDemoModuleAServiceREST/StartResponse")]
        System.Threading.Tasks.Task StartAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemoModuleAServiceREST/Stop", ReplyAction="http://tempuri.org/IDemoModuleAServiceREST/StopResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MosaicSample.UI.DemoModuleA.ServiceReference.IDemoModuleAServiceFault), Action="http://tempuri.org/IDemoModuleAServiceREST/StopIDemoModuleAServiceFaultFault", Name="IDemoModuleAServiceFault", Namespace="http://schemas.datacontract.org/2004/07/MosaicSample.DemoModuleA")]
        void Stop();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemoModuleAServiceREST/Stop", ReplyAction="http://tempuri.org/IDemoModuleAServiceREST/StopResponse")]
        System.Threading.Tasks.Task StopAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemoModuleAServiceREST/ResetAlarms", ReplyAction="http://tempuri.org/IDemoModuleAServiceREST/ResetAlarmsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MosaicSample.UI.DemoModuleA.ServiceReference.IDemoModuleAServiceFault), Action="http://tempuri.org/IDemoModuleAServiceREST/ResetAlarmsIDemoModuleAServiceFaultFau" +
            "lt", Name="IDemoModuleAServiceFault", Namespace="http://schemas.datacontract.org/2004/07/MosaicSample.DemoModuleA")]
        void ResetAlarms(int moduleInstance);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemoModuleAServiceREST/ResetAlarms", ReplyAction="http://tempuri.org/IDemoModuleAServiceREST/ResetAlarmsResponse")]
        System.Threading.Tasks.Task ResetAlarmsAsync(int moduleInstance);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemoModuleAServiceREST/SubscribeEvents", ReplyAction="http://tempuri.org/IDemoModuleAServiceREST/SubscribeEventsResponse")]
        void SubscribeEvents(int moduleInstance);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemoModuleAServiceREST/SubscribeEvents", ReplyAction="http://tempuri.org/IDemoModuleAServiceREST/SubscribeEventsResponse")]
        System.Threading.Tasks.Task SubscribeEventsAsync(int moduleInstance);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemoModuleAServiceREST/UnsubscribeEvents", ReplyAction="http://tempuri.org/IDemoModuleAServiceREST/UnsubscribeEventsResponse")]
        void UnsubscribeEvents(int moduleInstance);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemoModuleAServiceREST/UnsubscribeEvents", ReplyAction="http://tempuri.org/IDemoModuleAServiceREST/UnsubscribeEventsResponse")]
        System.Threading.Tasks.Task UnsubscribeEventsAsync(int moduleInstance);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDemoModuleAServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPlatformModuleWcfService/ModuleStateChanged")]
        void ModuleStateChanged(VP.FF.PT.Common.PlatformEssentials.Entities.DTOs.PlatformModuleDTO module);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPlatformModuleWcfService/MetricsChanged")]
        void MetricsChanged(VP.FF.PT.Common.PlatformEssentials.Entities.DTOs.MetricsDTO metrics);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPlatformModuleWcfService/SendUserNotification")]
        void SendUserNotification(VP.FF.PT.Common.PlatformEssentials.MessageType type, string message, System.TimeSpan duration);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDemoModuleAServiceChannel : MosaicSample.UI.DemoModuleA.ServiceReference.IDemoModuleAService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DemoModuleAServiceClient : System.ServiceModel.DuplexClientBase<MosaicSample.UI.DemoModuleA.ServiceReference.IDemoModuleAService>, MosaicSample.UI.DemoModuleA.ServiceReference.IDemoModuleAService {
        
        public DemoModuleAServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public DemoModuleAServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public DemoModuleAServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public DemoModuleAServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public DemoModuleAServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public bool KeepAlive() {
            return base.Channel.KeepAlive();
        }
        
        public System.Threading.Tasks.Task<bool> KeepAliveAsync() {
            return base.Channel.KeepAliveAsync();
        }
        
        public bool get_IsInitialized() {
            return base.Channel.get_IsInitialized();
        }
        
        public System.Threading.Tasks.Task<bool> get_IsInitializedAsync() {
            return base.Channel.get_IsInitializedAsync();
        }
        
        public void Start() {
            base.Channel.Start();
        }
        
        public System.Threading.Tasks.Task StartAsync() {
            return base.Channel.StartAsync();
        }
        
        public void Stop() {
            base.Channel.Stop();
        }
        
        public System.Threading.Tasks.Task StopAsync() {
            return base.Channel.StopAsync();
        }
        
        public void ResetAlarms(int moduleInstance) {
            base.Channel.ResetAlarms(moduleInstance);
        }
        
        public System.Threading.Tasks.Task ResetAlarmsAsync(int moduleInstance) {
            return base.Channel.ResetAlarmsAsync(moduleInstance);
        }
        
        public void SubscribeEvents(int moduleInstance) {
            base.Channel.SubscribeEvents(moduleInstance);
        }
        
        public System.Threading.Tasks.Task SubscribeEventsAsync(int moduleInstance) {
            return base.Channel.SubscribeEventsAsync(moduleInstance);
        }
        
        public void UnsubscribeEvents(int moduleInstance) {
            base.Channel.UnsubscribeEvents(moduleInstance);
        }
        
        public System.Threading.Tasks.Task UnsubscribeEventsAsync(int moduleInstance) {
            return base.Channel.UnsubscribeEventsAsync(moduleInstance);
        }
    }
}
