//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MosaicSample.UI.DemoModuleB.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IDemoModuleBServiceFault", Namespace="http://schemas.datacontract.org/2004/07/MosaicSample.DemoModuleB")]
    [System.SerializableAttribute()]
    public partial class IDemoModuleBServiceFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IDemoModuleBService", CallbackContract=typeof(MosaicSample.UI.DemoModuleB.ServiceReference.IDemoModuleBServiceCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IDemoModuleBService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemoModuleBServiceREST/KeepAlive", ReplyAction="http://tempuri.org/IDemoModuleBServiceREST/KeepAliveResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MosaicSample.UI.DemoModuleB.ServiceReference.IDemoModuleBServiceFault), Action="http://tempuri.org/IDemoModuleBServiceREST/KeepAliveIDemoModuleBServiceFaultFault" +
            "", Name="IDemoModuleBServiceFault", Namespace="http://schemas.datacontract.org/2004/07/MosaicSample.DemoModuleB")]
        bool KeepAlive();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemoModuleBServiceREST/KeepAlive", ReplyAction="http://tempuri.org/IDemoModuleBServiceREST/KeepAliveResponse")]
        System.Threading.Tasks.Task<bool> KeepAliveAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemoModuleBServiceREST/get_IsInitialized", ReplyAction="http://tempuri.org/IDemoModuleBServiceREST/get_IsInitializedResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MosaicSample.UI.DemoModuleB.ServiceReference.IDemoModuleBServiceFault), Action="http://tempuri.org/IDemoModuleBServiceREST/get_IsInitializedIDemoModuleBServiceFa" +
            "ultFault", Name="IDemoModuleBServiceFault", Namespace="http://schemas.datacontract.org/2004/07/MosaicSample.DemoModuleB")]
        bool get_IsInitialized();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemoModuleBServiceREST/get_IsInitialized", ReplyAction="http://tempuri.org/IDemoModuleBServiceREST/get_IsInitializedResponse")]
        System.Threading.Tasks.Task<bool> get_IsInitializedAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemoModuleBServiceREST/Start", ReplyAction="http://tempuri.org/IDemoModuleBServiceREST/StartResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MosaicSample.UI.DemoModuleB.ServiceReference.IDemoModuleBServiceFault), Action="http://tempuri.org/IDemoModuleBServiceREST/StartIDemoModuleBServiceFaultFault", Name="IDemoModuleBServiceFault", Namespace="http://schemas.datacontract.org/2004/07/MosaicSample.DemoModuleB")]
        void Start();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemoModuleBServiceREST/Start", ReplyAction="http://tempuri.org/IDemoModuleBServiceREST/StartResponse")]
        System.Threading.Tasks.Task StartAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemoModuleBServiceREST/Stop", ReplyAction="http://tempuri.org/IDemoModuleBServiceREST/StopResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MosaicSample.UI.DemoModuleB.ServiceReference.IDemoModuleBServiceFault), Action="http://tempuri.org/IDemoModuleBServiceREST/StopIDemoModuleBServiceFaultFault", Name="IDemoModuleBServiceFault", Namespace="http://schemas.datacontract.org/2004/07/MosaicSample.DemoModuleB")]
        void Stop();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemoModuleBServiceREST/Stop", ReplyAction="http://tempuri.org/IDemoModuleBServiceREST/StopResponse")]
        System.Threading.Tasks.Task StopAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemoModuleBServiceREST/ResetAlarms", ReplyAction="http://tempuri.org/IDemoModuleBServiceREST/ResetAlarmsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MosaicSample.UI.DemoModuleB.ServiceReference.IDemoModuleBServiceFault), Action="http://tempuri.org/IDemoModuleBServiceREST/ResetAlarmsIDemoModuleBServiceFaultFau" +
            "lt", Name="IDemoModuleBServiceFault", Namespace="http://schemas.datacontract.org/2004/07/MosaicSample.DemoModuleB")]
        void ResetAlarms(int moduleInstance);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemoModuleBServiceREST/ResetAlarms", ReplyAction="http://tempuri.org/IDemoModuleBServiceREST/ResetAlarmsResponse")]
        System.Threading.Tasks.Task ResetAlarmsAsync(int moduleInstance);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemoModuleBServiceREST/SubscribeEvents", ReplyAction="http://tempuri.org/IDemoModuleBServiceREST/SubscribeEventsResponse")]
        void SubscribeEvents(int moduleInstance);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemoModuleBServiceREST/SubscribeEvents", ReplyAction="http://tempuri.org/IDemoModuleBServiceREST/SubscribeEventsResponse")]
        System.Threading.Tasks.Task SubscribeEventsAsync(int moduleInstance);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemoModuleBServiceREST/UnsubscribeEvents", ReplyAction="http://tempuri.org/IDemoModuleBServiceREST/UnsubscribeEventsResponse")]
        void UnsubscribeEvents(int moduleInstance);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDemoModuleBServiceREST/UnsubscribeEvents", ReplyAction="http://tempuri.org/IDemoModuleBServiceREST/UnsubscribeEventsResponse")]
        System.Threading.Tasks.Task UnsubscribeEventsAsync(int moduleInstance);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDemoModuleBServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPlatformModuleWcfService/ModuleStateChanged")]
        void ModuleStateChanged(VP.FF.PT.Common.PlatformEssentials.Entities.DTOs.PlatformModuleDTO module);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPlatformModuleWcfService/MetricsChanged")]
        void MetricsChanged(VP.FF.PT.Common.PlatformEssentials.Entities.DTOs.MetricsDTO metrics);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPlatformModuleWcfService/SendUserNotification")]
        void SendUserNotification(VP.FF.PT.Common.PlatformEssentials.MessageType type, string message, System.TimeSpan duration);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDemoModuleBServiceChannel : MosaicSample.UI.DemoModuleB.ServiceReference.IDemoModuleBService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DemoModuleBServiceClient : System.ServiceModel.DuplexClientBase<MosaicSample.UI.DemoModuleB.ServiceReference.IDemoModuleBService>, MosaicSample.UI.DemoModuleB.ServiceReference.IDemoModuleBService {
        
        public DemoModuleBServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public DemoModuleBServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public DemoModuleBServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public DemoModuleBServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public DemoModuleBServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public bool KeepAlive() {
            return base.Channel.KeepAlive();
        }
        
        public System.Threading.Tasks.Task<bool> KeepAliveAsync() {
            return base.Channel.KeepAliveAsync();
        }
        
        public bool get_IsInitialized() {
            return base.Channel.get_IsInitialized();
        }
        
        public System.Threading.Tasks.Task<bool> get_IsInitializedAsync() {
            return base.Channel.get_IsInitializedAsync();
        }
        
        public void Start() {
            base.Channel.Start();
        }
        
        public System.Threading.Tasks.Task StartAsync() {
            return base.Channel.StartAsync();
        }
        
        public void Stop() {
            base.Channel.Stop();
        }
        
        public System.Threading.Tasks.Task StopAsync() {
            return base.Channel.StopAsync();
        }
        
        public void ResetAlarms(int moduleInstance) {
            base.Channel.ResetAlarms(moduleInstance);
        }
        
        public System.Threading.Tasks.Task ResetAlarmsAsync(int moduleInstance) {
            return base.Channel.ResetAlarmsAsync(moduleInstance);
        }
        
        public void SubscribeEvents(int moduleInstance) {
            base.Channel.SubscribeEvents(moduleInstance);
        }
        
        public System.Threading.Tasks.Task SubscribeEventsAsync(int moduleInstance) {
            return base.Channel.SubscribeEventsAsync(moduleInstance);
        }
        
        public void UnsubscribeEvents(int moduleInstance) {
            base.Channel.UnsubscribeEvents(moduleInstance);
        }
        
        public System.Threading.Tasks.Task UnsubscribeEventsAsync(int moduleInstance) {
            return base.Channel.UnsubscribeEventsAsync(moduleInstance);
        }
    }
}
